//
//  ShareObject.swift
//  GridAsync
//
//  Created by Hidayat Abisena on 07/02/24.
//

import SwiftUI

struct ShareObject: View {
    let photos: [Photo] = PhotoProvider.allPhotos()
    
    var body: some View {
        TabView {
            ForEach(photos) { photo in
                VStack(alignment: .leading, spacing: 10) {
                    photo.image
                        .resizable()
                        .scaledToFit()
                        .clipShape(RoundedRectangle(cornerRadius: 10))
                    
                    HStack {
                        Text(photo.caption)
                            .font(.headline)
                        
                        ShareLink(item: photo, preview: SharePreview(photo.caption, image: photo.image))
                    }
                    .foregroundStyle(.green)
                    Text(photo.description)
                }
                .padding()
            }
        }
        .tabViewStyle(PageTabViewStyle())
        .indexViewStyle(PageIndexViewStyle(backgroundDisplayMode: .always))
    }
}

#Preview {
    ShareObject()
        .preferredColorScheme(.dark)
}

struct Photo: Identifiable {
    var id = UUID()
    var image: Image
    var caption: String
    var description: String
}

struct PhotoProvider {
    static func allPhotos() -> [Photo] {
        let dummyData = [
            Photo(image: Image(.beach), caption: "Enjoy the beach", description: "This is the best beach that being generated by AI."),
            Photo(image: Image(.thecat2), caption: "Look at the cute cat", description: "This is the best beach that being generated by AI."),
            Photo(image: Image(.thecat4), caption: "Look at this cute cat", description: "This is the best beach that being generated by AI.")
        ]
        
        return dummyData
    }
}

extension Photo: Transferable {
    static var transferRepresentation: some TransferRepresentation {
        ProxyRepresentation(exporting: \.image)
    }
}
